# Generated by Django 6.1.1 on 2026-09-28 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True, verbose_name='IMEI')),
                ('sim_number', models.CharField(blank=True, max_length=20, verbose_name='شماره SIM')),
                ('management_status', models.CharField(choices=[('warehouse', 'در انبار'), ('sold', 'فروخته شده'), ('installed', 'نصب شده'), ('active', 'فعال'), ('faulty', 'خراب'), ('lost', 'گمشده'), ('stolen', 'سرقت شده'), ('disconnected', 'قطع سرویس'), ('retired', 'بازنشسته'), ('disposed', 'امحاء شده')], default='warehouse', max_length=20, verbose_name='وضعیت مدیریتی')),
                ('installed_at', models.DateField(blank=True, null=True, verbose_name='تاریخ نصب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دستگاه',
                'verbose_name_plural': 'دستگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('received', 'دریافت در سانا'), ('sold', 'فروش'), ('assigned_to_contract', 'اتصال به قرارداد'), ('removed_from_contract', 'خروج از قرارداد'), ('returned', 'بازگشت به سانا'), ('sent_to_repair', 'ارسال برای تعمیر'), ('repaired', 'اتمام تعمیر'), ('replaced', 'تعویض'), ('transferred', 'انتقال'), ('lost', 'گم\u200cشدن'), ('stolen', 'سرقت'), ('retired', 'بازنشستگی'), ('disposed', 'امحاء')], max_length=30, verbose_name='نوع رویداد')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ رویداد')),
                ('reason', models.CharField(blank=True, choices=[('repair', 'تعمیر'), ('replacement', 'تعویض'), ('contract_termination', 'پایان قرارداد'), ('customer_return', 'مرجوعی مشتری'), ('upgrade', 'ارتقاء'), ('defective', 'خرابی'), ('other', 'سایر')], max_length=30, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رویداد چرخه عمر دستگاه',
                'verbose_name_plural': 'رویدادهای چرخه عمر دستگاه',
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='سازنده')),
                ('name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('code', models.CharField(max_length=50, verbose_name='کد مدل')),
                ('protocol', models.CharField(max_length=50, verbose_name='پروتکل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مدل دستگاه',
                'verbose_name_plural': 'مدل\u200cهای دستگاه',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('mobile', models.CharField(max_length=15, verbose_name='موبایل')),
                ('personnel_code', models.CharField(blank=True, max_length=50, verbose_name='کد پرسنلی')),
                ('position', models.CharField(choices=[('driver', 'راننده'), ('senior', 'راننده ارشد'), ('supervisor', 'سرپرست رانندگان')], default='driver', max_length=20, verbose_name='سمت')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='شماره گواهینامه')),
                ('license_type', models.CharField(blank=True, max_length=50, verbose_name='نوع گواهینامه')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا گواهینامه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'رانندگان',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, verbose_name='پلاک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خودرو',
                'verbose_name_plural': 'خودروها',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع خودرو',
                'verbose_name_plural': 'انواع خودرو',
                'ordering': ['name'],
            },
        ),
    ]
