# Generated by Django 6.1.1 on 2026-09-28 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='organizations.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_devices', to=settings.AUTH_USER_MODEL, verbose_name='مالک شخصی'),
        ),
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_lifecycle_events', to='organizations.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='fleet.device', verbose_name='دستگاه'),
        ),
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_lifecycle_events', to='organizations.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_device_lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_lifecycle_events', to='organizations.subscription', verbose_name='قرارداد'),
        ),
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='fleet.devicemodel', verbose_name='مدل دستگاه'),
        ),
        migrations.AddField(
            model_name='driver',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='organizations.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='driver',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='organizations.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='organizations.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='organizations.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='مالک شخصی'),
        ),
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_lifecycle_events', to='fleet.vehicle', verbose_name='خودرو'),
        ),
        migrations.AddField(
            model_name='device',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='fleet.vehicle', verbose_name='خودرو'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='organizations.organization', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicletype', verbose_name='نوع خودرو'),
        ),
    ]
