# Generated by Django 6.1.1

import django.db.models.deletion
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReplacementRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_type', models.CharField(choices=[('temporary_repair', 'جایگزینی موقت برای تعمیر'), ('permanent_replacement', 'تعویض دائمی')], max_length=30, verbose_name='نوع جایگزینی')),
                ('replacement_date', models.DateTimeField(default=timezone.now, verbose_name='تاریخ جایگزینی')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replacement_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_relations_as_replacement', to='fleet.device', verbose_name='دستگاه جایگزین')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_relations_as_source', to='fleet.device', verbose_name='دستگاه قبلی')),
            ],
            options={
                'verbose_name': 'رابطه جایگزینی دستگاه',
                'verbose_name_plural': 'روابط جایگزینی دستگاه‌ها',
                'ordering': ['-replacement_date', '-id'],
            },
        ),
    ]
