# Generated by Django 6.1.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_devicereplacementrelation'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_holder_organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='held_devices',
                to='organizations.organization',
                verbose_name='تحویل‌گیرنده فعلی',
            ),
        ),
        migrations.AddField(
            model_name='device',
            name='current_holder_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='held_devices_personal',
                to=settings.AUTH_USER_MODEL,
                verbose_name='تحویل‌گیرنده شخصی',
            ),
        ),
        migrations.CreateModel(
            name='DeviceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(
                    choices=[
                        ('return_for_repair', 'بازگشت برای تعمیر'),
                        ('repaired', 'اتمام تعمیر'),
                        ('temporary_replacement', 'جایگزینی موقت'),
                        ('permanent_replacement', 'تعویض دائمی'),
                        ('lost', 'گم‌شدن'),
                        ('stolen', 'سرقت'),
                        ('transfer_customer', 'انتقال به مشتری دیگر'),
                        ('transfer_branch', 'انتقال بین شعب'),
                        ('transfer_vehicle', 'انتقال بین خودروها'),
                        ('retire', 'بازنشستگی'),
                        ('dispose', 'امحاء'),
                    ],
                    max_length=40,
                    verbose_name='نوع عملیات',
                )),
                ('replacement_type', models.CharField(
                    blank=True,
                    choices=[
                        ('temporary_repair', 'جایگزینی موقت برای تعمیر'),
                        ('permanent_replacement', 'تعویض دائمی'),
                    ],
                    max_length=30,
                    verbose_name='نوع جایگزینی',
                )),
                ('reason', models.CharField(blank=True, max_length=30, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت جدید')),
                ('performed_at', models.DateTimeField(default=timezone.now, verbose_name='زمان عملیات')),
                ('device', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='operations',
                    to='fleet.device',
                    verbose_name='دستگاه',
                )),
                ('replacement_device', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='replacement_operations',
                    to='fleet.device',
                    verbose_name='دستگاه جایگزین',
                )),
                ('subscription', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='device_operations',
                    to='organizations.subscription',
                    verbose_name='قرارداد',
                )),
                ('target_subscription', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='target_device_operations',
                    to='organizations.subscription',
                    verbose_name='قرارداد مقصد',
                )),
                ('target_organization', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='target_device_operations',
                    to='organizations.organization',
                    verbose_name='سازمان مقصد',
                )),
                ('target_user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='target_device_operations',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='کاربر مقصد',
                )),
                ('target_branch', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='target_device_operations',
                    to='organizations.branch',
                    verbose_name='شعبه مقصد',
                )),
                ('target_vehicle', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='target_device_operations',
                    to='fleet.vehicle',
                    verbose_name='خودرو مقصد',
                )),
                ('performed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='device_operations',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='انجام‌دهنده',
                )),
            ],
            options={
                'verbose_name': 'عملیات دستگاه',
                'verbose_name_plural': 'عملیات دستگاه',
                'ordering': ['-performed_at', '-id'],
            },
        ),
    ]
