# Generated by Django 6.1.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_deviceoperation_device_custody'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='device_operation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lifecycle_events',
                to='fleet.deviceoperation',
                verbose_name='عملیات دستگاه',
            ),
        ),
    ]
