# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_devicelifecycleevent_device_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceoperation',
            name='replacement_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('loaner', 'امانی / موقت'),
                    ('sold', 'فروش به مشتری'),
                    ('free_exchange', 'تعویض بدون هزینه'),
                    ('paid_exchange', 'تعویض با هزینه'),
                    ('warranty', 'تعویض گارانتی'),
                    ('refurbished', 'دستگاه بازسازی‌شده'),
                    ('other', 'سایر'),
                ],
                max_length=30,
                verbose_name='نحوه تجاری جایگزینی',
            ),
        ),
        migrations.AddField(
            model_name='deviceoperation',
            name='repair_return_action',
            field=models.CharField(
                blank=True,
                choices=[
                    ('return_customer_same_vehicle', 'بازگشت به مشتری و نصب روی همان خودرو'),
                    ('return_customer_no_vehicle', 'بازگشت به مشتری بدون نصب'),
                    ('sana_warehouse', 'بازگشت به انبار سانا'),
                    ('customer_spare', 'تحویل به مشتری به عنوان دستگاه یدکی'),
                    ('install_other_vehicle', 'نصب روی خودروی دیگر'),
                    ('transfer_customer', 'انتقال به مشتری دیگر'),
                    ('retire', 'بازنشستگی'),
                    ('dispose', 'امحاء'),
                    ('other', 'سایر'),
                ],
                max_length=40,
                verbose_name='سرنوشت دستگاه پس از تعمیر',
            ),
        ),
    ]
