# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_deviceoperation_outcome_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceoperation',
            old_name='repair_return_action',
            new_name='outcome_action',
        ),
        migrations.AlterField(
            model_name='device',
            name='management_status',
            field=models.CharField(
                choices=[
                    ('warehouse', 'در انبار'),
                    ('sold', 'فروخته شده'),
                    ('installed', 'نصب شده'),
                    ('active', 'فعال'),
                    ('ready', 'آماده تعیین تکلیف'),
                    ('faulty', 'خراب'),
                    ('lost', 'گمشده'),
                    ('stolen', 'سرقت شده'),
                    ('disconnected', 'قطع سرویس'),
                    ('retired', 'بازنشسته'),
                    ('disposed', 'امحاء شده'),
                ],
                default='warehouse',
                max_length=20,
                verbose_name='وضعیت مدیریتی',
            ),
        ),
        migrations.AlterField(
            model_name='deviceoperation',
            name='operation_type',
            field=models.CharField(
                choices=[
                    ('return_for_repair', 'بازگشت برای تعمیر'),
                    ('repaired', 'اتمام تعمیر'),
                    ('found', 'پیدا شدن دستگاه'),
                    ('disposition', 'تعیین تکلیف دستگاه'),
                    ('temporary_replacement', 'جایگزینی موقت'),
                    ('permanent_replacement', 'تعویض دائمی'),
                    ('lost', 'گم‌شدن'),
                    ('stolen', 'سرقت'),
                    ('transfer_customer', 'انتقال به مشتری دیگر'),
                    ('transfer_branch', 'انتقال بین شعب'),
                    ('transfer_vehicle', 'انتقال بین خودروها'),
                    ('retire', 'بازنشستگی'),
                    ('dispose', 'امحاء'),
                ],
                max_length=40,
                verbose_name='نوع عملیات',
            ),
        ),
        migrations.AlterField(
            model_name='deviceoperation',
            name='outcome_action',
            field=models.CharField(
                blank=True,
                choices=[
                    ('return_customer_same_vehicle', 'بازگشت به مشتری و نصب روی همان خودرو'),
                    ('return_customer_no_vehicle', 'بازگشت به مشتری بدون نصب'),
                    ('sana_warehouse', 'بازگشت به انبار سانا'),
                    ('customer_spare', 'تحویل به مشتری به عنوان دستگاه یدکی'),
                    ('install_other_vehicle', 'نصب روی خودروی دیگر'),
                    ('transfer_customer', 'انتقال به مشتری دیگر'),
                    ('retire', 'بازنشستگی'),
                    ('dispose', 'امحاء'),
                    ('other', 'سایر'),
                ],
                max_length=40,
                verbose_name='تعیین تکلیف دستگاه',
            ),
        ),
        migrations.AlterField(
            model_name='devicelifecycleevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('received', 'دریافت در سانا'),
                    ('sold', 'فروش'),
                    ('assigned_to_contract', 'اتصال به قرارداد'),
                    ('removed_from_contract', 'خروج از قرارداد'),
                    ('returned', 'بازگشت به سانا'),
                    ('sent_to_repair', 'ارسال برای تعمیر'),
                    ('repaired', 'اتمام تعمیر'),
                    ('replaced', 'تعویض'),
                    ('transferred', 'انتقال'),
                    ('lost', 'گم‌شدن'),
                    ('found', 'پیدا شدن'),
                    ('disposition', 'تعیین تکلیف'),
                    ('stolen', 'سرقت'),
                    ('retired', 'بازنشستگی'),
                    ('disposed', 'امحاء'),
                ],
                max_length=30,
                verbose_name='نوع رویداد',
            ),
        ),
    ]
