# Generated by Django 6.1.1 on 2026-10-10 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_gpstelemetry_normalized'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='drivervehicleassignment',
            new_name='fleet_drive_driver__66f323_idx',
            old_name='fleet_drive_driver_i_7a0d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='drivervehicleassignment',
            new_name='fleet_drive_vehicle_1a6d4e_idx',
            old_name='fleet_drive_vehicle_i_4f7f7a_idx',
        ),
        migrations.AlterField(
            model_name='devicelifecycleevent',
            name='event_type',
            field=models.CharField(choices=[('received', 'دریافت در سانا'), ('sold', 'فروش'), ('assigned_to_contract', 'اتصال به قرارداد'), ('removed_from_contract', 'خروج از قرارداد'), ('returned', 'بازگشت به سانا'), ('sent_to_repair', 'ارسال برای تعمیر'), ('repaired', 'اتمام تعمیر'), ('replaced', 'تعویض'), ('transferred', 'انتقال'), ('lost', 'گم\u200cشدن'), ('found', 'پیدا شدن'), ('disposition', 'تعیین تکلیف'), ('stolen', 'سرقت'), ('retired', 'بازنشستگی'), ('disposed', 'امحاء')], max_length=30, verbose_name='نوع رویداد'),
        ),
        migrations.AlterField(
            model_name='gpstelemetry',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_telemetry', to='fleet.device', verbose_name='دستگاه'),
        ),
        migrations.AlterField(
            model_name='gpstelemetry',
            name='gps_time',
            field=models.DateTimeField(verbose_name='زمان GPS'),
        ),
        migrations.AlterField(
            model_name='gpstelemetry',
            name='protocol',
            field=models.CharField(max_length=50, verbose_name='پروتکل'),
        ),
        migrations.AlterField(
            model_name='gpstelemetry',
            name='raw_payload',
            field=models.BinaryField(verbose_name='بسته خام'),
        ),
        migrations.AlterField(
            model_name='gpstelemetry',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان دریافت'),
        ),
    ]
