# Generated by Django 6.1.1

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.utils import timezone


def backfill_device_history(apps, schema_editor):
    Device = apps.get_model('fleet', 'Device')
    DeviceOwnershipHistory = apps.get_model('fleet', 'DeviceOwnershipHistory')
    DeviceCustomerAccessPeriod = apps.get_model('fleet', 'DeviceCustomerAccessPeriod')

    for device in Device.objects.all().iterator():
        organization_id = device.organization_id or device.current_holder_organization_id
        user_id = device.owner_user_id or device.current_holder_user_id

        if organization_id:
            DeviceOwnershipHistory.objects.get_or_create(
                device_id=device.id,
                ended_at__isnull=True,
                defaults={
                    'organization_id': organization_id,
                    'owner_user_id': None,
                    'reason': 'migration',
                },
            )
        elif user_id:
            DeviceOwnershipHistory.objects.get_or_create(
                device_id=device.id,
                ended_at__isnull=True,
                defaults={
                    'organization_id': None,
                    'owner_user_id': user_id,
                    'reason': 'migration',
                },
            )

        active_link = device.subscription_links.filter(unassigned_at__isnull=True).first()
        if (organization_id or user_id) and device.management_status not in {'warehouse', 'disposed'}:
            DeviceCustomerAccessPeriod.objects.get_or_create(
                device_id=device.id,
                ended_at__isnull=True,
                defaults={
                    'organization_id': organization_id,
                    'user_id': None if organization_id else user_id,
                    'subscription_id': active_link.subscription_id if active_link else None,
                    'branch_id': device.branch_id,
                    'reason': 'migration',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_refine_device_outcomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=timezone.now, verbose_name='شروع مالکیت')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان مالکیت')),
                ('reason', models.CharField(blank=True, max_length=40, verbose_name='دلیل تغییر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='fleet.device', verbose_name='دستگاه')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_ownership_history', to='organizations.organization', verbose_name='سازمان مالک')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_ownership_history', to=settings.AUTH_USER_MODEL, verbose_name='مالک شخصی')),
            ],
            options={
                'verbose_name': 'سابقه مالکیت دستگاه',
                'verbose_name_plural': 'سوابق مالکیت دستگاه‌ها',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceownershiphistory',
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(('organization__isnull', False), ('owner_user__isnull', True)))
                    | (models.Q(('organization__isnull', True), ('owner_user__isnull', False)))
                ),
                name='device_ownership_one_customer',
            ),
        ),
        migrations.CreateModel(
            name='DeviceCustomerAccessPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=timezone.now, verbose_name='شروع دسترسی')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان دسترسی')),
                ('reason', models.CharField(blank=True, max_length=40, verbose_name='دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_access_periods', to='fleet.device', verbose_name='دستگاه')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_access_periods', to='organizations.organization', verbose_name='سازمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_access_periods', to=settings.AUTH_USER_MODEL, verbose_name='کاربر شخصی')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_access_periods', to='organizations.subscription', verbose_name='قرارداد مرتبط')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_access_periods', to='organizations.branch', verbose_name='شعبه مرتبط')),
            ],
            options={
                'verbose_name': 'بازه دسترسی مشتری به دستگاه',
                'verbose_name_plural': 'بازه‌های دسترسی مشتری به دستگاه',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='devicecustomeraccessperiod',
            index=models.Index(fields=['device', 'started_at', 'ended_at'], name='fleet_device_device_i_3f4a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecustomeraccessperiod',
            index=models.Index(fields=['organization', 'started_at', 'ended_at'], name='fleet_device_organiz_2b2f24_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecustomeraccessperiod',
            index=models.Index(fields=['user', 'started_at', 'ended_at'], name='fleet_device_user_id_2d7d8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicecustomeraccessperiod',
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(('organization__isnull', False), ('user__isnull', True)))
                    | (models.Q(('organization__isnull', True), ('user__isnull', False)))
                ),
                name='device_access_one_customer',
            ),
        ),
        migrations.RunPython(backfill_device_history, migrations.RunPython.noop),
    ]
