# Generated by Django 6.1.1 on 2026-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_rename_fleet_drive_driver_i_7a0d2f_idx_fleet_drive_driver__66f323_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gpstelemetry',
            index=models.Index(fields=['device', 'received_at'], name='fleet_gps_device_received_idx'),
        ),
        migrations.AddConstraint(
            model_name='gpstelemetry',
            constraint=models.UniqueConstraint(fields=('device', 'fingerprint'), name='fleet_gps_device_fingerprint_uniq'),
        ),
    ]
