# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_device_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicecustomeraccessperiod',
            new_name='fleet_devic_device__208b12_idx',
            old_name='fleet_device_device_i_3f4a8d_idx',
        ),
        migrations.RenameIndex(
            model_name='devicecustomeraccessperiod',
            new_name='fleet_devic_organiz_72e79d_idx',
            old_name='fleet_device_organiz_2b2f24_idx',
        ),
        migrations.RenameIndex(
            model_name='devicecustomeraccessperiod',
            new_name='fleet_devic_user_id_4680fb_idx',
            old_name='fleet_device_user_id_2d7d8a_idx',
        ),
        migrations.AlterField(
            model_name='devicelifecycleevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('received', 'دریافت در سانا'),
                    ('sold', 'فروش'),
                    ('assigned_to_contract', 'اتصال به قرارداد'),
                    ('removed_from_contract', 'خروج از قرارداد'),
                    ('returned', 'بازگشت به سانا'),
                    ('sent_to_repair', 'ارسال برای تعمیر'),
                    ('repaired', 'اتمام تعمیر'),
                    ('replaced', 'تعویض'),
                    ('transferred', 'انتقال'),
                    ('lost', 'گم‌شدن'),
                    ('disposition', 'تعیین تکلیف'),
                    ('stolen', 'سرقت'),
                    ('retired', 'بازنشستگی'),
                    ('disposed', 'امحاء'),
                ],
                max_length=30,
                verbose_name='نوع رویداد',
            ),
        ),
    ]
